#name of the workflow
name: CI

#event that triggers the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: install dependencies
        run: | 
          pip install -r app/requirements.txt
          pip install ruff

      - name: Lint with ruff
        run: ruff check app/

      - name: Build Docker image
        run: docker build -t cloud-native:${{ github.sha }} ./app